### ISSUE TITLE
Products resolver issues

### ISSUE THREAD

**Issue by leon0v** [deity-io/falcon#437] opened 2019-05-08 09:08 UTC
**Describe the bug**
The [falcon-magento2-api](https://github.com/deity-io/falcon/tree/dev/packages/falcon-magento2-api) doesn't correctly resolve all fields in products() query.

**To Reproduce**
For example the url_path, image and thumbnail fields 
![image](https://user-images.githubusercontent.com/17271164/57362965-45a98180-7180-11e9-9484-e02186b6c112.png)

Also the urlPath field does not resolve, which results in the following error:
![image](https://user-images.githubusercontent.com/17271164/57363227-f152d180-7180-11e9-8430-36d13d37da76.png)

Here the error is caused because the `reduceProduct()` function calls [data.urlPath](https://github.com/deity-io/falcon/blob/dev/packages/falcon-magento2-api/src/index.js#L612) which doesnt exist.

This should be data.customAttributes.urlKey, but this again doesnt work for the category resolver.

It does work with the category query

Also the pagination does not work with products query

**Expected behavior**
Get correct values

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Browser: chrome
 - Version Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by leon0v** [comment] 2019-05-08 09:32
Or has this to do with Magento api version?

**Comment by leon0v** [comment] 2019-05-08 14:26
Seems the urlpath problem is already addressed in #308

**Comment by Borales** [comment] 2019-05-08 21:27
Hi, @leon0v 

This is going to be fixed with the upcoming changes to our Magento module. If you don't mind - I'm gonna close this issue as a duplicate of #308 (it's gonna be referenced to that task).

**Closed** 2019-05-09 13:05 UTC
