### ISSUE TITLE
Loadable-stats.json has a hardcoded import path

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#276] opened 2019-01-21 08:42 UTC
**Describe the bug**
It appears in a very specific case scenario. 

When you build a production bundle on a CI server, `loadable-stats.json` gets hardcoded in `build/server.js` file, and when you later deploy this bundle to the production server and try to run it - Node complains that there's no such file (`/path-on-ci/build/loadable-stats.json` != `/path-on-prod/build/loadable-stats.json`).

**Comment by tutok** [comment] 2019-01-21 08:49
Maybe it is caused by `smartRequire` from `@loadable/server/lib/util`. We have webpack AssetManifest.json which is resolved in the exactly same way (except requiring, we use `require` instead of `smartRequire`) and it works. Will look on that.

**Closed** 2019-03-05 08:57 UTC
Labels: automation, bug, node
