### ISSUE TITLE
yarn start of server crashes with `customerToken` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by andreasemer** [deity-io/falcon#40] opened 2018-10-04 21:26 UTC
**Describe the bug**
After you want to start the falcon server with "yarn start" the error 
```shell 
error: FalconServer: Cannot destructure property `customerToken` of 'undefined' or 'null'.
[2018-10-04 23:13:30:804] error: FalconServer: Initialization error - cannot start the server
[2018-10-04 23:13:30:805] error: TypeError: Cannot destructure property `customerToken` of 'undefined' or 'null'.
```
appear. 

I have tested this with the default demo Magento Shop (snapshot.deity.io) and a local one.

**To Reproduce**
1. Clone this repo with git
2. yarn install the packages
3. create an app with "yarn create falcon-app my-app" or "yarn create falcon-app --example shop-with-blog my-app"
4. cd in "my-app/server" 
5. Try to start the app with "yarn start"

**Expected behavior**
The server should start without errors.

**Screenshots**
```shell
andreas in ~/Code/deity.test/mothership/server on
⚡ yarn start
yarn run v1.10.1
$ cross-env NODE_ENV=development nodemon index.js
[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
GET https://snapshot.deity.io/blog-api/wp/v2/blog/info (183ms)
[2018-10-04 23:13:30:683] info: Retrieving Magento token.
POST https://snapshot.deity.io/rest/default/V1/integration/admin/token (117ms)
[2018-10-04 23:13:30:803] error: FalconServer: Cannot destructure property `customerToken` of 'undefined' or 'null'.
[2018-10-04 23:13:30:804] error: FalconServer: Initialization error - cannot start the server
[2018-10-04 23:13:30:805] error: TypeError: Cannot destructure property `customerToken` of 'undefined' or 'null'.
    at Magento2Api.didEncounterError (/Users/andreas/Code/deity.test/mothership/server/node_modules/@deity/falcon-magento2-api/src/Magento2ApiBase.js:284:49)
    at Magento2Api.<anonymous> (/Users/andreas/Code/deity.test/mothership/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:155:30)
    at Generator.throw (<anonymous>)
    at rejected (/Users/andreas/Code/deity.test/mothership/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[nodemon] app crashed - waiting for file changes before starting...
```

**Versions:**
 - Node v10.11.0
 - Yarn 1.10.1
 - OS: OsX 10.14

**Comment by Stevie-Ray** [comment] 2018-10-05 08:14
same issue here 👍

**Comment by Borales** [comment] 2018-10-05 08:16
@andreasemer @Stevie-Ray we're working on it right now

**Comment by mateuszwozniak** [comment] 2018-10-05 08:44
@andreasemer @Stevie-Ray the problem is fixed as it was an issue on our Magneto2 server. We'll leave this bug open as we'll add some more verbose error logging for such cases.

**Comment by andreasemer** [comment] 2018-10-05 19:37
@mateuszwozniak Thank you very much, i can confirm, that this error doesn't appear anymore with the default server config, which conntects to your server. 

What was the problem? If i try to connect to my local M2 server the same error appear.

**Comment by mateuszwozniak** [comment] 2018-10-05 19:58
It was a problem with authorization of the user that's used for API access. Have you got already [our M2 module](https://github.com/deity-io/falcon-magento2-module) installed in your Magento 2 setup and configured as in the description of that module?

**Comment by andreasemer** [comment] 2018-10-05 20:01
Here was the problem, it was a wrong url, thx :-)

**Comment by Borales** [comment] 2018-10-09 11:37
Hi @andreasemer, please close this issue if you don't have this problem anymore

**Comment by andreasemer** [comment] 2018-10-09 11:44
@mateuszwozniak Wrote "We'll leave this bug open as we'll add some more verbose error logging for such cases.", but for me it's ok to close this ticket.

**Comment by Borales** [comment] 2018-10-09 11:47
@andreasemer we merged an improved "error logging" for Magento2 API just now, so such error messages should be more informative in future.

**Comment by Borales** [comment] 2018-10-12 10:40
Reopening this issue as it appears to be not solved completely

**Comment by hobadams** [comment] 2018-10-12 10:53
> Here was the problem, it was a wrong url in the magento config, thx :-)

Hey @andreasemer, I'm having the same issue. Everything works when pointing at `snapshot.deity.io` but not when pointing at a local instance. Which config did you change to get it working? 

Thanks for any help.

**Comment by andreasemer** [comment] 2018-10-12 15:37
Make sure that the configuration in your magento store in "Stores" -> "Configuration" -> "Deity" -> "Magento API" is correct. Also double check that the settings in your Deity Server config file (default.json) is correct, maybe you have to change the "protocol" to "http" on your local machine.

**Comment by cane-lagerwaard** [comment] 2018-10-24 13:46
@hobadams Hi Hob, did you manage to get it working?

**Comment by hobadams** [comment] 2018-10-24 14:14
@cane-lagerwaard not yet. I'll take a look tomorrow. I suspect changing my local to be http could solve the issue. Happy to close the issue for now and re open if it persists.

**Closed** 2018-10-24 19:44 UTC
Labels: bug, confirmed
